# Run NATS server
services:
  nats:
    image: nats:2.9.20-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./nats.conf:/etc/nats/nats-server.conf
  
  exporter:
    image: natsio/prometheus-nats-exporter:0.12.0
    command: [
      "-connz",
      "-routez",
      "-subz",
      "-varz",
      "-prefix=nats",
      "-use_internal_server_id",
      "http://nats:8222/"
    ]
    depends_on:
      - nats
  
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - 9091:9090

  consumer:
    image: test/nats:latest
    command: ["python3", "consumer.py"]
    depends_on:
      - nats

  consumer2:
    image: test/nats:latest
    command: ["python3", "consumer.py"]
    depends_on:
      - nats
